---
title: "Variância e Covariância"
---

***

<br>
<font size = 4> 
Textos de referência: 

  * **[Econometria Básica][4]** - *Damodar N. Gujarati; Dawn C. Porter*
  

    Apêndice A - Revisão de alguns conceitos estatísticos

<br>

***

# Variância

Seja $X$ uma variável aleatória e seja $E(X)=\mu$. A distribuição, ou dispersão, dos valores de $X$ em torno do valor esperado pode ser mensurada pela variÂncia, definida como  

<br>

$$
var(X)=\sigma_X^2=E(X-\mu)^2
$$

<br>

A raiz quadrada positiva de $\sigma^2_X$, $\sigma_X$ é definida como **desvio padrão** de $X$. A variância, ou desvio padrão, indica quão próximos ou distantes os valores individuais de $X$ estão distribuídos em torno de seu valor médio.  

A variância definida previamente é calculada como se segue:  

$$
var(X)=\sum_x (X-\mu)^2f(x) \ \ \ \ \ \ \ \ \ \ \text{se for uma variável aleatória discreta} \\\
var(X)=\int_{-\inf}^\inf (X-\mu)^2f(x)dx \ \ \ \ \ \ \ \ \ \ \text{se X for uma variável aleatória contínua} 
$$

<br>

Para conveniência de cálculo, a fórmula da variância apresentada pode ser expressa como  

<br>

$$
var(x)=\sigma^2_x=E(X-\mu)^2 \\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ =E(X^2)-\mu^2 \\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \  =E(X^2)-[E(X)]^2
$$

***

## *Propriedades da Variância*

<br>

  1. $E(X-\mu)^2=E(X^2)-\mu^2$, como observado anteriormente.  
  
  
  2. A variância de uma constante é zero.  
  

  3. Se $a$ e $b$ são constantes, então  

$$
var(aX+b)=a^2 \ var(X)
$$

  4. Se $X$ e $Y$ são variáveis aleatórias *independentes*, então
  
$$
var(X+Y)=var(X)+(Y) \\ var(X-Y)=var(X)+(Y)
$$

<center> Isso pode ser generalizado para mais do que duas variáveis independentes.  </center>

<br>

5. Se $X$ e $Y$ são variáveis aleatórias *independentes*, e $a$ e $b$ são constantes,  

$$
var(aX+bY)=a^2 \ var(x)+b^2 \ var(Y)
$$

<br> 

***

# Covariância

Seja $X$ e $Y$ duas variáveis aleatórias com médias $\mu_x$ e $\mu_y$, respectivamente. Então, a **covariância** entre as duas variáveis é definida como:  

$$
Cov(X,Y)=E(X-\mu_x)(Y-\mu_y)=E(XY)-\mu_x\mu_y 
$$

<br>

A variância de uma única variável é a covariância daquela variável com ela mesma.  

A covariância é calculada como se segue:  

$$
Cov(X,Y)=\sum_y \sum_x (X-\mu_x)(Y-\mu_y)f(x,y) \\ \ \ \ \ \ \ \ \ =\sum_y \sum_x XYf(x,y)-\mu_x\mu_y
$$

se $X$ e $Y$ são variáveis aleatórias discretas, e

$$
Cov(X,Y)=\int_{-\inf}^{\inf}\int_{-\inf}^{\inf}(X-\mu_x)(Y-\mu_y)f(x,y) \ dx \ dy \\ \ \ \ \ \ \ \ =\int_{-\inf}^{\inf}\int_{-\inf}^{\inf}XYf(x,y) \ dx \ dy -\mu_x\mu_y
$$

se $X$ e $Y$ são variáveis aleatórias contínuas.  

***

## *Propriedades da Covariância*  

<br>

**1.** Se $X$ e $Y$ são independentes, a sua covariância é zero, pois  
  
$$
Cov(X,Y)=E(XY)-\mu_x\mu_y \\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ = \mu_x\mu_y-\mu_x\mu_y \\ =0 \ \ \ \ 
$$

uma vez que $E(XY)=E(X)E(Y)=\mu_x\mu_y$ quando $X$ e $Y$ são independentes.

<br>

**2.**  
  
$$
Cov(a+bX, \ \ c \ + \ dY)=bd \ Cov(X,Y)
$$

em que $a$, $b$, $c$ e $d$ são constantes.

<br>

***

# Coeficiente de Correlação  

O coeficiente de correlação (população) $\rho$ (rho) é definido como:  

<br>

$$
\rho=\frac{Cov(X,Y)}{\sqrt{var(x) \ var(Y)}}=\frac{Cov(X,Y)}{\sigma_x\sigma_y}
$$

<br>

Assim definido, $\rho$ é uma medida de associação *linear* entre duas variáveis e situa-se entre $-1$, indicando associação negativa perfeita, e $+1$, indicando associação positiva perfeita.  

Por meio da fórmula anterior podemos verificar que  

$$
Cov(X,Y)=\rho \ \sigma_x\sigma_y
$$
<br>

***

### *Variâncias de variáveis correlacionadas*  

Sejam $X$ e $Y$ as duas variáveis aleatórias. Então,  

$$
var(X+Y)=var(X)+var(Y)+2 \ Cov(X,Y) \\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ =var(X)+var(Y)+2\rho\sigma+x\sigma_y \\ var(X-Y)=var(X)+var(Y)-2 \ Cov(X,Y) \\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ =var(X)+var(Y)-2\rho\sigma+x\sigma_y 
$$

<br>

Os resultados anteriores podem ser generalizados como se segue:  

$$
var \ ( \ \sum^n_{i=1}x_i \ )=\sum^n_{i=1}var \ X_i \ + \ 2\sum\sum_{i<j} Cov(X_i, \ X_j) \\ = \sum^n_{i=1}var \ X_i \ + \ 2\sum\sum_{i<j}\rho_{ij}\sigma_i\sigma_j
$$

<br>

em que $\rho_{ij}$ é o coeficiente de correlação entre $X_i$ e $X_j$ e $\sigma_i$ e $\sigma_j$ são os desvios padrão de $X_i$ e $X_j$.  

<br>

***

$$\Re$$

***

</font>






[1]:https://www.saraiva.com.br/estatistica-basica-9-ed-2017-9748081/p
[2]:https://www.ime.usp.br/~pam/scriptsR.html 
[4]:https://books.google.com.br/books/about/Econometria_B%C3%A1sica.html?id=bOLX3aXf6y0C&printsec=frontcover&source=kp_read_button&redir_esc=y#v=onepage&q&f=false